# print('a'.isidentifier())
# print('_'.isidentifier())
# print('7y'.isidentifier())
# print(' '.isspace())
# print('    '.isspace())
# print(''.isspace())
# print(' k  '.isspace())
# print(isinstance('hello',int))
# print(isinstance('hello',float))
# print(isinstance('hello',str))
# print(isinstance(7,str))
# print(isinstance(76,float))
# print(isinstance(787,int))
# print(isinstance(4.6,str))
# print(isinstance(6.8,int))
# print(isinstance(6.8,float))
